UI_TEXTS = {
    "app": {
        "name": "Frogger Rally",
        "tagline": "La rana del bosque",
        "footer": "© 2026 Todos los derechos reservados • Built with Python & Django • UX/UI Interface • Deployed on Render ®",
    },
    "index": {
        "meta_description": "Frogger Rally: aventura arcade con estética de quest, reflejos, estrategia y acción en cada cruce.",
        "title": "Frogger Rally · Quest",
        "main_aria": "Frogger Rally con estética animalista",
        "topbar_aria": "Opciones del juego",
        "brand_aria": "Identidad del juego",
        "nav_aria": "Secciones de Frogger Rally",
        "ranking_link": "Ranking",
        "guide_button": "Guía",
        "visual_settings": "Ajustes visuales",
        "visual_theme": "Tema visual",
        "theme_quest": "Quest",
        "theme_nocturne": "Nocturno",
        "theme_sunset": "Atardecer",
        "visual_mode": "Modo gráfico",
        "mode_illustrated": "Ilustrado",
        "mode_emoji": "Emojis",
        "play_aria": "Iniciar juego y configurar partida",
        "start_button": "Jugar ahora",
        "hero_aria": "Presentación animalista de Frogger Rally",
        "combo_chip": "Combo x4",
        "hud_level": "Nivel",
        "hud_score": "Puntaje",
        "hud_lives": "Vidas",
        "hud_time": "Tiempo",
        "hud_streak": "Racha",
        "hud_best": "Mejor",
        "canvas_aria": "Tablero del juego Frogger Rally con estética animalista",
        "touch_aria": "Controles táctiles con flechas",
        "move_up": "Mover arriba",
        "move_left": "Mover izquierda",
        "move_down": "Mover abajo",
        "move_right": "Mover derecha",
        "initial_message": "Enter para iniciar. Guía siempre a la rana con flechas, WASD, swipe o botones.",
        "close_setup": "Cerrar configuración",
        "setup_eyebrow": "Prepará tu salto",
        "setup_title": "Elegí dificultad, especie y escenario",
        "difficulty": "Dificultad",
        "easy": "Fácil",
        "medium": "Media",
        "hard": "Difícil",
        "species": "Especie",
        "species_aria": "Especie de rana",
        "green_tree": "Rana verde arbórea",
        "red_eye": "Rana de ojos rojos",
        "poison_dart": "Rana dardo venenosa",
        "tomato": "Rana tomate",
        "glass": "Rana de cristal",
        "scenario": "Escenario",
        "city": "Ciudad",
        "forest": "Bosque",
        "snow": "Nieve",
        "desert": "Desierto",
        "mixed": "Ruta, lago y bosque",
        "frog_info": "Verde suave, vientre crema y ojos dorados.",
        "confirm_start": "Comenzar partida",
        "close_guide": "Cerrar guía",
        "guide_title": "Guía rápida",
        "guide_items": [
            "Usá flechas, WASD, swipe o botones táctiles para moverte.",
            "Cruzá caminos y arroyos hasta ocupar las hojas iluminadas.",
            "Recolectá bonus para sumar puntos, tiempo o protección.",
        ],
    },
    "ranking": {
        "title": "Ranking · Frogger Rally",
        "main_aria": "Ranking de Frogger Rally",
        "topbar_aria": "Navegación del ranking",
        "nav_aria": "Secciones",
        "back_link": "Volver al juego",
        "eyebrow": "Ranking",
        "heading": "Mejores partidas",
        "description": "Tu mejor puntaje local aparece debajo. Próximamente se integrará un ranking global persistente.",
        "best_local": "Mejor puntaje local",
    },
}
